### PR TITLE
my dish ui page implemented

### PR DESCRIPTION
**Pull request by DreXuri**
page for my single dish for an authourized user

### CODE REVIEW

**Comment by DreXuri** [comment]
can we merge this it the mydish page @ikennaumeh @moak13

**Comment by moak13** [comment]
> can we merge this it the mydish page @ikennaumeh @moak13

I think this is the same as dish/home so no need for this.

**Comment by DreXuri** [comment]
Ok

**Comment by DreXuri** [comment]
hello @moak13 was this the pr you were referring to?

**Pull request closed without merging**
